package bg.sofia.uni.fmi.mjt.todoist.command.enums;

public enum CommandType {
    REGISTER, LOGIN, LOGOUT, DISCONNECT,
    HELP_TASK, HELP_COLLABORATION, HELP_LABEL,
    ADD_TASK, UPDATE_TASK, DELETE_TASK, GET_TASK, LIST_TASKS, LIST_DASHBOARD, FINISH_TASK,
    ADD_COLLABORATION, DELETE_COLLABORATION, LIST_COLLABORATIONS, ADD_USER, ASSIGN_TASK, LIST_TASKS_COLLABORATION,
    LIST_USERS,
    ADD_LABEL, DELETE_LABEL, LIST_LABELS, LABEL_TASK
}
